FROM node:20-alpine AS install-stage

WORKDIR /app
COPY . .

RUN npm ci

FROM node:20-alpine AS build-stage
COPY --from=install-stage /app /app
WORKDIR /app

RUN npm run lint && \
    npm run build && \
    npm run test

FROM node:20-alpine AS run-stage
COPY --from=build-stage /app /app
WORKDIR /app

EXPOSE 8080

CMD ["npm", "start"]


