# build stage
FROM node:20-alpine AS build-stage

WORKDIR /app
COPY . .
RUN npm install
RUN npm run lint && \
    npm run build && \
    npm run test

# production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY prod_nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
